In [7]:
import pandas as pd

In [27]:
a = pd.read_csv('data/2018년데이터.csv', encoding = 'euc_kr')
a

     소재지  WiFi 접속자수  자동차등록수  사업체수   총인구수    세대수   주택수    아파트수    면수
0    한림읍   420383.0   12431  2174  25003  10204   933   733.0    53
1    애월읍   695233.0   22053  2514  36550  15563  2114   824.0    36
2    구좌읍   534957.0    9112  1738  16283   7670   333    90.0     4
3    조천읍   863303.0   13781  1873  24718  10538  1533   508.0   175
4    한경면   271661.0    5743   720   9447   4657    44     NaN     0
5    추자면        NaN     822   214   2149   1049     7     NaN     0
6    우도면    95615.0    1223   305   1892    999     6     NaN    38
7   일도1동   356614.0    1086  1326   2993   1623   151   110.0   486
8   일도2동  1524817.0   14907  2210  34684  13187  1537  4716.0   690
9   이도1동   584394.0    3211  1532   7989   3677   234  1053.0   592
10  이도2동  1455341.0   37535  5162  50137  19526  4967  5089.0  1700
11  삼도1동   515924.0   12714  1367  14345   5952   718  1056.0   151
12  삼도2동   164619.0    3618  1029   8662   4161   501   682.0   618
13  용담1동   276242.0    3888   805   7610   3543   602   226.0    55
14  용담2동  1067146.0   21714  1113  15673   6456   876  1067.0   773
15   건입동   821032.0    4357   750   9857   4235   815  1041.0   370
16   화북동  1204150.0   14971  1546  25391   9542  1665  5148.0   324
17   삼양동   399091.0   12501  1000  25153   9273  1111  5215.0   656
18   봉개동   365427.0    3547   269   4936   2094   428   129.0   327
19   아라동  1362600.0   17815  2049  34321  13337  4065  3103.0   821
20   오라동   115860.0   11514   978  14906   5565  2480   479.0   971
21    연동  1702776.0  141225  4649  43217  19336  4450  5741.0   832
22   노형동  2591152.0   54617  4476  56223  21026  4321  9043.0  1587
23   외도동   518913.0   11471  1185  21741   8167  1482  3510.0   514
24   이호동    58805.0    5320   281   4654   1829   572   232.0   804
25   도두동    52102.0    8885   991   3257   1412   217   126.0   897

In [35]:
a['주차장부족자동차수'] = a['자동차등록수'] - a['세대수']
a['주차장확보율'] = a['면수']/a['자동차등록수']*100
a['wifi 가중치'] = a['WiFi 접속자수']*0.2
a

,소재지,WiFi 접속자수,자동차등록수,사업체수,총인구수,세대수,주택수,아파트수,면수,주차장부족자동차수,wifi 가중치,주차장확보율
0,한림읍,420383.0,12431,2174,25003,10204,933,733.0,53,2227,84076.6,0.426353
1,애월읍,695233.0,22053,2514,36550,15563,2114,824.0,36,6490,139046.6,0.163243
2,구좌읍,534957.0,9112,1738,16283,7670,333,90.0,4,1442,106991.4,0.043898
3,조천읍,863303.0,13781,1873,24718,10538,1533,508.0,175,3243,172660.6,1.269864
4,한경면,271661.0,5743,720,9447,4657,44,NaN,0,1086,54332.2,0.000000
5,추자면,NaN,822,214,2149,1049,7,NaN,0,-227,NaN,0.000000
6,우도면,95615.0,1223,305,1892,999,6,NaN,38,224,19123.0,3.107114
7,일도1동,356614.0,1086,1326,2993,1623,151,110.0,486,-537,71322.8,44.751381
8,일도2동,1524817.0,14907,2210,34684,13187,1537,4716.0,690,1720,304963.4,4.628698
9,이도1동,584394.0,3211,1532,7989,3677,234,1053.0,592,-466,116878.8,18.436624
10,이도2동,1455341.0,37535,5162,50137,19526,4967,5089.0,1700,18009,291068.2,4.529106
11,삼도1동,515924.0,12714,1367,14345,5952,718,1056.0,151,6762,103184.8,1.187667
12,삼도2동,164619.0,3618,1029,8662,4161,501,682.0,618,-543,32923.8,17.081260
13,용담1동,276242.0,3888,805,7610,3543,602,226.0,55,345,55248.4,1.414609
14,용담2동,1067146.0,21714,1113,15673,6456,876,1067.0,773,15258,213429.2,3.559915
15,건입동,821032.0,4357,750,9857,4235,815,1041.0,370,122,164206.4,8.492082
16,화북동,1204150.0,14971,1546,25391,9542,1665,5148.0,324,5429,240830.0,2.164184
17,삼양동,399091.0,12501,1000,25153,9273,1111,5215.0,656,3228,79818.2,5.247580
18,봉개동,365427.0,3547,269,4936,2094,428,129.0,327,1453,73085.4,9.219058
19,아라동,1362600.0,17815,2049,34321,13337,4065,3103.0,821,4478,272520.0,4.608476
20,오라동,115860.0,11514,978,14906,5565,2480,479.0,971,5949,23172.0,8.433212
21,연동,1702776.0,141225,4649,43217,19336,4450,5741.0,832,121889,340555.2,0.589131
22,노형동,2591152.0,54617,4476,56223,21026,4321,9043.0,1587,33591,518230.4,2.905689
23,외도동,518913.0,11471,1185,21741,8167,1482,3510.0,514,3304,103782.6,4.480865
24,이호동,58805.0,5320,281,4654,1829,572,232.0,804,3491,11761.0,15.112782
25,도두동,52102.0,8885,991,3257,1412,217,126.0,897,7473,10420.4,10.095667

In [32]:
# b = a.drop(['자동차등록수', '세대수', '총인구수'], axis = 1)
# b

     소재지  WiFi 접속자수  사업체수   주택수    아파트수    면수  주차장부족자동차수  wifi 가중치
0    한림읍   420383.0  2174   933   733.0    53       2227   84076.6
1    애월읍   695233.0  2514  2114   824.0    36       6490  139046.6
2    구좌읍   534957.0  1738   333    90.0     4       1442  106991.4
3    조천읍   863303.0  1873  1533   508.0   175       3243  172660.6
4    한경면   271661.0   720    44     NaN     0       1086   54332.2
5    추자면        NaN   214     7     NaN     0       -227       NaN
6    우도면    95615.0   305     6     NaN    38        224   19123.0
7   일도1동   356614.0  1326   151   110.0   486       -537   71322.8
8   일도2동  1524817.0  2210  1537  4716.0   690       1720  304963.4
9   이도1동   584394.0  1532   234  1053.0   592       -466  116878.8
10  이도2동  1455341.0  5162  4967  5089.0  1700      18009  291068.2
11  삼도1동   515924.0  1367   718  1056.0   151       6762  103184.8
12  삼도2동   164619.0  1029   501   682.0   618       -543   32923.8
13  용담1동   276242.0   805   602   226.0    55        345   55248.4
14  용담2동  1067146.0  1113   876  1067.0   773      15258  213429.2
15   건입동   821032.0   750   815  1041.0   370        122  164206.4
16   화북동  1204150.0  1546  1665  5148.0   324       5429  240830.0
17   삼양동   399091.0  1000  1111  5215.0   656       3228   79818.2
18   봉개동   365427.0   269   428   129.0   327       1453   73085.4
19   아라동  1362600.0  2049  4065  3103.0   821       4478  272520.0
20   오라동   115860.0   978  2480   479.0   971       5949   23172.0
21    연동  1702776.0  4649  4450  5741.0   832     121889  340555.2
22   노형동  2591152.0  4476  4321  9043.0  1587      33591  518230.4
23   외도동   518913.0  1185  1482  3510.0   514       3304  103782.6
24   이호동    58805.0   281   572   232.0   804       3491   11761.0
25   도두동    52102.0   991   217   126.0   897       7473   10420.4

In [36]:
a.corr()

,WiFi 접속자수,자동차등록수,사업체수,총인구수,세대수,주택수,아파트수,면수,주차장부족자동차수,wifi 가중치,주차장확보율
WiFi 접속자수,1.000000,0.632347,0.800463,0.859188,0.847012,0.776053,0.828965,0.545127,0.523564,1.000000,-0.278366
자동차등록수,0.632347,1.000000,0.752565,0.650102,0.700631,0.705017,0.583803,0.410455,0.984013,0.632347,-0.248348
사업체수,0.800463,0.752565,1.000000,0.901444,0.919905,0.858642,0.692180,0.598933,0.642533,0.800463,-0.190129
총인구수,0.859188,0.650102,0.901444,1.000000,0.993349,0.893351,0.819900,0.550492,0.505458,0.859188,-0.378912
세대수,0.847012,0.700631,0.919905,0.993349,1.000000,0.887955,0.778942,0.504847,0.562355,0.847012,-0.388980
주택수,0.776053,0.705017,0.858642,0.893351,0.887955,1.000000,0.721018,0.696059,0.595404,0.776053,-0.257417
아파트수,0.828965,0.583803,0.692180,0.819900,0.778942,0.721018,1.000000,0.596692,0.486691,0.828965,-0.302582
면수,0.545127,0.410455,0.598933,0.550492,0.504847,0.696059,0.596692,1.000000,0.349663,0.545127,0.177548
주차장부족자동차수,0.523564,0.984013,0.642533,0.505458,0.562355,0.595404,0.486691,0.349663,1.000000,0.523564,-0.190719
wifi 가중치,1.000000,0.632347,0.800463,0.859188,0.847012,0.776053,0.828965,0.545127,0.523564,1.000000,-0.278366
주차장확보율,-0.278366,-0.248348,-0.190129,-0.378912,-0.388980,-0.257417,-0.302582,0.177548,-0.190719,-0.278366,1.000000